//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottom()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int BottomsID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Occassion { get; set; }
        public int BottomTypesID { get; set; }
    
        public virtual BottomType BottomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfit> Outfits { get; set; }
    }
}
